company:
  email: developer@yyfly.com
  name: YYFLY
  website: www.yyfly.com
project:
  copyright: yyfly
  description: yyfly common
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  name: yyfly-common
  type: common
  version: 0.0.1-SNAPSHOT
